### ISSUE TITLE
No colours in Linux or Windows

### ISSUE THREAD

**Issue by benmarwick** [hadley/colformat#11]
I'm not seeing any colour in the output on Linux or Windows. Is there something else I need to install? What is a console that supports colour? That would be helpful to know for using this package.

Here's my RStudio console in Windows: 

![col_win](https://user-images.githubusercontent.com/1262179/27007558-da6a9786-4e0b-11e7-8269-75fbd8e5d3f9.png)

Here's my RStudio console in Linux: 

![col_linux](https://user-images.githubusercontent.com/1262179/27007560-dee9570c-4e0b-11e7-8e2c-d81304d8365a.png)

**Comment by krlmlr** [comment]
Coloring requires a nightly build of RStudio. Last time I checked I haven't found an option to enable the colored console in the configuration dialog, but that may have been added by now. I was able to turn it on by tweaking a configuration file.

Do you see colors if you run R from the terminal?

**Comment by hadley** [comment]
You need a daily

**Comment by benmarwick** [comment]
Yep, thanks. I got yesterday's daily for Windows, and now I can see the colours. Looks great!

![image](https://user-images.githubusercontent.com/1262179/27015162-91cda98a-4ebc-11e7-808f-b67f22500f6d.png)
