### ISSUE TITLE
setting string max length?

### ISSUE THREAD

**Issue by randomgambit** [hadley/colformat#13]
hello everyone, thanks for your great work! 

Just wondering if there are any plans about implementing that? I think its pretty useful. For instance, in `Pandas` one could simply do:

```
In [43]: df = pd.DataFrame(np.array([['foo', 'bar', 'bim', 'uncomfortably long string'],
   ....:                             ['horse', 'cow', 'banana', 'apple']]))
   ....: 

In [44]: pd.set_option('max_colwidth',40)

In [45]: df
Out[45]: 
       0    1       2                          3
0    foo  bar     bim  uncomfortably long string
1  horse  cow  banana                      apple

In [46]: pd.set_option('max_colwidth', 6)

In [47]: df
Out[47]: 
       0    1      2      3
0    foo  bar    bim  un...
1  horse  cow  ba...  apple

In [48]: pd.reset_option('max_colwidth')
```

which is really helpful when one prints a `tibble` that contains both text and numeric values.

**Comment by hadley** [comment]
It already exists?

<img width="543" alt="screen shot 2017-06-19 at 9 41 38 am" src="https://user-images.githubusercontent.com/4196/27290658-88806daa-54d3-11e7-8cc2-72b3ba5c8cce.png">
