### ISSUE TITLE
Change default styling of NA

### ISSUE THREAD

**Issue by krlmlr** [hadley/colformat#15]
to work better on dark consoles. https://github.com/hadley/colformat/pull/14#pullrequestreview-47386608

**Comment by krlmlr** [comment]
@hadley: Could you please look into this? Maybe just passing `as = "white"` in `style_na()` is enough, but I'm not sure.

**Comment by hadley** [comment]
Yeah, I think that's probably the right approach.

**Comment by hadley** [comment]
You mean `as = "black"` right?

**Comment by krlmlr** [comment]
No, `as = "black"` looked ugly on my system. YMMV.

**Comment by krlmlr** [comment]
Seems to be ok now.
