### ISSUE TITLE
Possible update of reference to earliest usage of technique

### ISSUE THREAD

**Issue by leondutoit** [hadley/colformat#5]
Hi

This looks like a great package. I noticed the reference to sparklines being first used in 2009. Edward Tufte actually wrote about this technique in The Visual Display of Quantitative Data back in 1983. A good discussion of the history of his usage and prior art can be found here: https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=000AIr

Perhaps this link can be included in the readme? It certainly is interesting!

Best
Leon

**Comment by hadley** [comment]
That's prior art for sparklines, not generating sparklines with unicode characters. I'll clarify that.
